// <auto-generated />
using HealthcareApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthcareApp.API.Models.Appointment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("AvailabilityId").HasColumnType("int");
                b.Property<DateTime>("BookedAt").HasColumnType("datetime2");
                b.Property<int>("DoctorId").HasColumnType("int");
                b.Property<string>("DoctorNotes").HasColumnType("nvarchar(max)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<int>("PatientId").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("AvailabilityId").IsUnique();
                b.HasIndex("DoctorId");
                b.HasIndex("PatientId");
                b.ToTable("Appointments");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Availability", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("Date").HasColumnType("datetime2");
                b.Property<int>("DoctorId").HasColumnType("int");
                b.Property<TimeSpan>("EndTime").HasColumnType("time");
                b.Property<bool>("IsBooked").HasColumnType("bit");
                b.Property<TimeSpan>("StartTime").HasColumnType("time");
                b.HasKey("Id");
                b.HasIndex("DoctorId");
                b.ToTable("Availabilities");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Doctor", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Bio").HasColumnType("nvarchar(max)");
                b.Property<string>("Phone").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("ProfileImage").HasColumnType("nvarchar(max)");
                b.Property<int>("SpecializationId").HasColumnType("int");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("SpecializationId");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Doctors");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Patient", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime?>("DateOfBirth").HasColumnType("datetime2");
                b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();
                b.ToTable("Patients");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Specialization", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Description").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Specializations");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(450)");
                b.Property<string>("FullName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Appointment", b =>
            {
                b.HasOne("HealthcareApp.API.Models.Availability", "Availability")
                    .WithOne("Appointment")
                    .HasForeignKey("HealthcareApp.API.Models.Appointment", "AvailabilityId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HealthcareApp.API.Models.Doctor", "Doctor")
                    .WithMany("Appointments")
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HealthcareApp.API.Models.Patient", "Patient")
                    .WithMany("Appointments")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Availability");
                b.Navigation("Doctor");
                b.Navigation("Patient");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Availability", b =>
            {
                b.HasOne("HealthcareApp.API.Models.Doctor", "Doctor")
                    .WithMany("Availabilities")
                    .HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Doctor");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Doctor", b =>
            {
                b.HasOne("HealthcareApp.API.Models.Specialization", "Specialization")
                    .WithMany("Doctors")
                    .HasForeignKey("SpecializationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("HealthcareApp.API.Models.User", "User")
                    .WithOne("Doctor")
                    .HasForeignKey("HealthcareApp.API.Models.Doctor", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Specialization");
                b.Navigation("User");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Patient", b =>
            {
                b.HasOne("HealthcareApp.API.Models.User", "User")
                    .WithOne("Patient")
                    .HasForeignKey("HealthcareApp.API.Models.Patient", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Specialization", b =>
            {
                b.Navigation("Doctors");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.User", b =>
            {
                b.Navigation("Doctor");
                b.Navigation("Patient");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Doctor", b =>
            {
                b.Navigation("Appointments");
                b.Navigation("Availabilities");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Patient", b =>
            {
                b.Navigation("Appointments");
            });

            modelBuilder.Entity("HealthcareApp.API.Models.Availability", b =>
            {
                b.Navigation("Appointment");
            });
#pragma warning restore 612, 618
        }
    }
}
